application: bandsongifier
version: 1
runtime: go
api_version: go1

handlers:
- url: /scripts
  static_dir: dist/scripts
  secure: always
- url: /fonts
  static_dir: dist/fonts
  mime_type: application/x-font-otf
  secure: always
- url: /lib
  static_dir: dist/lib
  secure: always
- url: /assets
  static_dir: dist/assets
  secure: always
- url: /styles
  static_dir: dist/styles
  secure: always
- url: /views
  static_dir: dist/views
  secure: always
- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^node_modules$
- ^design$
- ^public$
- ^e2e$
- ^gulp$
- ^.tmp$
- ^.sass-cache$
- ^test$